# Generated by Django 3.2.20 on 2024-12-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230802_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default.webp', upload_to='profile_pics', verbose_name='Фото'),
        ),
    ]
