# Generated by Django 3.2.20 on 2025-07-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiteStudent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_status',
            field=models.CharField(blank=True, choices=[('ML1', 'Младший тренер 1'), ('ML2', 'Младший тренер 2'), ('ST1', 'Старший тренер 1'), ('ST2', 'Старший тренер 2'), ('V', 'Высший тренер')], max_length=3, null=True, verbose_name='Статус учителя'),
        ),
    ]
