# Generated by Django 3.2.20 on 2023-09-02 18:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('1', 'Первая четверть'), ('2', 'Вторая четверть'), ('3', 'Третья четверть'), ('4', 'Четвертая четверть')], max_length=1, verbose_name='Четверть')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата проведения урока')),
                ('status', models.CharField(choices=[('P', 'Проведен'), ('NP', 'Не проведен'), ('Z', 'Замена'), ('O', 'Отменен')], default='NP', max_length=2, verbose_name='Статус урока')),
                ('reason_for_not_held', models.TextField(blank=True, null=True, verbose_name='Причина непроведения урока')),
                ('hours', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Часы')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='StudyGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование типа группы')),
                ('payment', models.PositiveIntegerField(verbose_name='Оплата за час')),
            ],
            options={
                'verbose_name': 'Тип учебной группы',
                'verbose_name_plural': 'Типы учебных групп',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование предмета')),
            ],
            options={
                'verbose_name': 'Учебный предмет',
                'verbose_name_plural': 'Учебные предметы',
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование типа группы')),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduprocesses.studygrouptype', verbose_name='Тип группы')),
                ('students', models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Студенты')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduprocesses.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(blank=True, choices=[('PR', 'Пришел на урок'), ('ABS-R', 'Не пришел на урок с причиной'), ('ABS-NR', 'Не пришел на урок без причины')], max_length=10, null=True, verbose_name='Статус посещения')),
                ('reason_for_absent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Причина непосещения')),
                ('mark', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduprocesses.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Успеваемость ученика',
                'verbose_name_plural': 'Успеваемость учеников',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='study_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduprocesses.studygroup', verbose_name='Учебная группа'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Замененный учитель'),
        ),
    ]
