# Generated by Django 3.2.20 on 2023-09-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprocesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester1',
            fields=[
            ],
            options={
                'verbose_name': 'Урок первой четверти',
                'verbose_name_plural': 'Уроки первой четверти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eduprocesses.lesson',),
        ),
        migrations.CreateModel(
            name='Semester2',
            fields=[
            ],
            options={
                'verbose_name': 'Урок второй четверти',
                'verbose_name_plural': 'Уроки второй четверти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eduprocesses.lesson',),
        ),
        migrations.CreateModel(
            name='Semester3',
            fields=[
            ],
            options={
                'verbose_name': 'Урок третей четверти',
                'verbose_name_plural': 'Уроки третей четверти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eduprocesses.lesson',),
        ),
        migrations.CreateModel(
            name='Semester4',
            fields=[
            ],
            options={
                'verbose_name': 'Урок четвертой четверти',
                'verbose_name_plural': 'Уроки четвертой четверти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eduprocesses.lesson',),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='hours',
            field=models.FloatField(default=1, verbose_name='Часы'),
        ),
    ]
