# Generated by Django 3.2.20 on 2023-10-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprocesses', '0002_auto_20230926_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
    ]
