# Generated by Django 3.2.20 on 2024-09-17 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprocesses', '0003_lesson_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='coins',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Монеты'),
        ),
    ]
