# Generated by Django 3.2.20 on 2024-09-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprocesses', '0004_studentattendance_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
    ]
