# Generated by Django 3.2.20 on 2024-10-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprocesses', '0005_alter_studentattendance_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='Домашнее задание'),
        ),
    ]
