# Generated by Django 3.2.20 on 2024-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprocesses', '0006_lesson_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='max_grade',
            field=models.SmallIntegerField(default=10, verbose_name='Максимальная оценка'),
        ),
    ]
