# Generated by Django 3.2.20 on 2025-07-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprocesses', '0007_lesson_max_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester1',
            options={'verbose_name': 'Урок первой четверти', 'verbose_name_plural': 'Уpоки первой четверти'},
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='group_type',
            field=models.CharField(choices=[('I', 'Индивид'), ('M', 'Мини-группа'), ('P', 'Полная группа'), ('S', 'Супер-группа')], max_length=1, verbose_name='Тип группы'),
        ),
    ]
