# Generated by Django 3.2.20 on 2025-07-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduprocesses', '0008_auto_20250703_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduprocesses.studygrouptype', verbose_name='Тип группы'),
        ),
    ]
