# Generated by Django 3.2.20 on 2025-07-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprocesses', '0009_alter_studygroup_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='homework_completed',
            field=models.BooleanField(blank=True, help_text='Отметка о выполнении домашнего задания к этому уроку', null=True, verbose_name='Выполнил домашнее задание'),
        ),
    ]
