# Generated by Django 3.2.20 on 2025-07-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprocesses', '0010_studentattendance_homework_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester1',
        ),
        migrations.DeleteModel(
            name='Semester2',
        ),
        migrations.DeleteModel(
            name='Semester3',
        ),
        migrations.DeleteModel(
            name='Semester4',
        ),
        migrations.CreateModel(
            name='HalfYear1',
            fields=[
            ],
            options={
                'verbose_name': 'Урок первого полугодия',
                'verbose_name_plural': 'Уpоки первого полугодия',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eduprocesses.lesson',),
        ),
        migrations.CreateModel(
            name='HalfYear2',
            fields=[
            ],
            options={
                'verbose_name': 'Урок второго полугодия',
                'verbose_name_plural': 'Уроки второго полугодия',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eduprocesses.lesson',),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='quarter',
            field=models.CharField(choices=[('1', 'Первое полугодие'), ('2', 'Второе полугодие')], max_length=1, verbose_name='Полугодие'),
        ),
    ]
