# Generated by Django 3.2.20 on 2025-07-16 06:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekly_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('week_end', models.DateField(verbose_name='Конец недели')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Еженедельный тест',
                'verbose_name_plural': 'Еженедельные тесты',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyTestSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('order', models.PositiveIntegerField(help_text='Порядок от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Порядок отображения')),
                ('weekly_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='weekly_tests.weeklytest', verbose_name='Еженедельный тест')),
            ],
            options={
                'verbose_name': 'Предмет еженедельного теста',
                'verbose_name_plural': 'Предметы еженедельного теста',
                'ordering': ['weekly_test', 'order'],
                'unique_together': {('weekly_test', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, help_text='Балл от 0 до 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Балл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Студент'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_tests.weeklytestsubject', verbose_name='Предмет')),
                ('weekly_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_tests.weeklytest', verbose_name='Еженедельный тест')),
            ],
            options={
                'verbose_name': 'Результат еженедельного теста',
                'verbose_name_plural': 'Результаты еженедельного теста',
                'ordering': ['weekly_test', 'student', 'subject__order'],
                'unique_together': {('weekly_test', 'student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Средний балл')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('weekly_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_tests.weeklytest', verbose_name='Еженедельный тест')),
            ],
            options={
                'verbose_name': 'Доска почета',
                'verbose_name_plural': 'Доска почета',
                'ordering': ['position'],
                'unique_together': {('weekly_test', 'student')},
            },
        ),
    ]
