# Generated by Django 3.2.20 on 2025-07-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_tests', '0002_weeklyleaderboard_weeklytest_weeklytestresult_weeklytestsubject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklytestresult',
            options={'ordering': ['weekly_test', 'student', 'subject__id'], 'verbose_name': 'Результат еженедельного теста', 'verbose_name_plural': 'Результаты еженедельного теста'},
        ),
        migrations.AlterModelOptions(
            name='weeklytestsubject',
            options={'ordering': ['weekly_test', 'id'], 'verbose_name': 'Предмет еженедельного теста', 'verbose_name_plural': 'Предметы еженедельного теста'},
        ),
        migrations.AlterUniqueTogether(
            name='weeklytestsubject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='weeklytestsubject',
            name='order',
        ),
    ]
