# Generated by Django 3.2.20 on 2025-07-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_tests', '0003_auto_20250716_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyLeaderboard',
        ),
    ]
