# Generated by Django 3.2.20 on 2024-04-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubject',
            name='time_limit_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
