# Generated by Django 3.2.20 on 2024-05-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer', '0002_auto_20240429_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubject',
            name='shuffle_options',
            field=models.BooleanField(default=True, verbose_name='Перемешать варианты ответов'),
        ),
    ]
