# Generated by Django 3.2.20 on 2025-07-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizer', '0003_quizsubject_shuffle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='excel_files/', verbose_name='Файл Excel с контентом тестирования'),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='quiz_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizer.quizsubject', verbose_name='Предмет теста'),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='quizsubject',
            name='language',
            field=models.CharField(choices=[('RUS', 'Русский'), ('KAZ', 'Казахский')], default='RUS', max_length=9, verbose_name='Язык теста'),
        ),
        migrations.AlterField(
            model_name='quizsubject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='quizsubject',
            name='time_limit_minutes',
            field=models.IntegerField(default=10, verbose_name='Время на тест (минуты)'),
        ),
    ]
