# Generated by Django 3.2.20 on 2025-02-09 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Тестовый вопрос (cвободное тестирование)',
                'verbose_name_plural': 'Вопросы тестов (cвободное тестирование)',
            },
        ),
        migrations.CreateModel(
            name='OpenQuizSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('KAZ', 'Казахский')], default='RUS', max_length=9, verbose_name='Язык')),
                ('time_limit_minutes', models.IntegerField(default=10, verbose_name='Лимит времени')),
            ],
            options={
                'verbose_name': 'Предмет теста (свободное тесирование)',
                'verbose_name_plural': 'Предметы тестов (свободное тесирование)',
            },
        ),
        migrations.CreateModel(
            name='OpenUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_quiz.openquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ответы пользователей (свободное тестирование)',
                'verbose_name_plural': 'Ответы пользователей (свободное тестирование)',
            },
        ),
        migrations.AddField(
            model_name='openquestion',
            name='quiz_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_quiz.openquizsubject'),
        ),
    ]
