# Generated by Django 3.2.20 on 2025-02-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='open_excel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_quiz.openquizsubject')),
            ],
            options={
                'verbose_name': 'Файл Excel (свободное тестирование)',
                'verbose_name_plural': 'Файлы Excel (свободное тестирование)',
            },
        ),
    ]
