# Generated by Django 3.2.20 on 2025-02-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_quiz', '0002_openexcelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='openquestion',
            name='weight',
            field=models.SmallIntegerField(default=1, verbose_name='Баллы'),
        ),
    ]
