# Generated by Django 3.2.20 on 2024-10-12 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Таргет',
                'verbose_name_plural': 'Таргет',
            },
        ),
        migrations.CreateModel(
            name='RegularVideoCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Обычный видеокурс',
                'verbose_name_plural': 'Обычные видеокурсы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eduapp.videocourse',),
        ),
        migrations.CreateModel(
            name='TargetVideoCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Курс для таргета',
                'verbose_name_plural': 'Курсы для таргета',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eduapp.videocourse',),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='is_target_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='subject',
            field=models.CharField(default=0, max_length=255, verbose_name='Название курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='dur_kaz',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='dur_rus',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
    ]
