# Generated by Django 3.2.20 on 2024-12-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0002_auto_20241013_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='image',
            field=models.ImageField(default='cu-1.webp', upload_to='courses', verbose_name='Фото'),
        ),
    ]
