# Generated by Django 3.2.20 on 2025-07-04 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eduapp', '0003_alter_videocourse_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('idea', 'Идея'), ('bug', 'Ошибка'), ('question', 'Вопрос'), ('other', 'Другое')], max_length=10)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пожелание по улучшению системы',
                'verbose_name_plural': 'Пожелания по улучшению системы',
            },
        ),
    ]
