# Generated by Django 3.2.20 on 2025-07-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senim_store', '0002_auto_20240918_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercoins',
            options={'verbose_name': 'Коины пользователя', 'verbose_name_plural': 'Коины пользователей'},
        ),
    ]
